### ISSUE TITLE
Undocumented dependencies

### ISSUE THREAD

**Issue by JBlumenberg** [thtuerk/kochbuch#1]
Leider fehlen dependicies, wie der PHPMailer. 

Für mich ist jedoch kein Fix nötig - ich habe offensichtlich viel zu wenig Ahnung von Git+Webserver, als dass ich das Tool installieren könnte :-)

**Comment by thtuerk** [comment]
Ich habe nicht detailliert dokumentiert, welche Dependencies nötig sind und auch die Installationsanleitung ist sehr lückenhaft. Der Code war eher für Leute gedacht, die es sich selbst anpassen wollen und sich mit PHP, Latex, Pandoc etc. genug auskennen, um den Code als Grundlage zu verwenden und für die eigenen Bedürfnisse stark anzupassen. Daher habe ich keine Arbeit investiert, um eine komfortable Installation zu gewährleisten.

Ich habe jetzt ein Repo mit Docker-Dateien aufgesetzt, die eine geeignete Umgebung zur Verfügung stellen: https://github.com/thtuerk/kochbuch-docker

Vielleicht hilft das ja.

**Comment by JBlumenberg** [comment]
Ich wollte wirklich keine Arbeit verursachen. Das ist sehr nett, vielen Dank!
